import json

with open('Colab.ipynb', 'r') as f:
    nb = json.load(f)

for cell in nb['cells']:
    if cell.get('source') and any('uvicorn' in line for line in cell['source']):
        cell['source'] = [
            'import os\n',
            'import subprocess\n',
            'import time\n',
            'import re\n',
            'import threading\n',
            'import sys\n',
            'from getpass import getpass\n',
            '\n',
            'def start_localtunnel(port):\n',
            '    proc = subprocess.Popen(["npx", "localtunnel", "--port", str(port), "--local-host", "127.0.0.1"], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n',
            '    url = None\n',
            '    for _ in range(30):\n',
            '        line = proc.stdout.readline()\n',
            '        match = re.search(r"(https://[^\s]+)", line)\n',
            '        if match:\n',
            '            url = match.group(1)\n',
            '            break\n',
            '    return proc, url\n',
            '\n',
            'def stream_logs(process, prefix):\n',
            '    for line in iter(process.stdout.readline, ""):\n',
            '        if line:\n',
            '            print(f"[{prefix}] {line.strip()}")\n',
            '            sys.stdout.flush()\n',
            '\n',
            '# Expose API via Localtunnel\n',
            'api_proc, api_url = start_localtunnel(8000)\n',
            'print(f"==================================================")\n',
            'print(f"🔗 BACKEND API URL: {api_url}")\n',
            'print(f"👉 VERY IMPORTANT: Click the Backend API URL above and click \\"Click to Continue\\" BEFORE using the frontend!")\n',
            'print(f"==================================================")\n',
            '\n',
            'os.environ["DATABASE_URL"] = "postgresql+asyncpg://videoai:videoai@localhost:5432/videoai"\n',
            'os.environ["DATABASE_URL_SYNC"] = "postgresql+psycopg2://videoai:videoai@localhost:5432/videoai"\n',
            'os.environ["REDIS_URL"] = "redis://localhost:6379/0"\n',
            'os.environ["CELERY_BROKER_URL"] = "redis://localhost:6379/0"\n',
            'os.environ["CELERY_RESULT_BACKEND"] = "redis://localhost:6379/1"\n',
            'os.environ["NEXT_PUBLIC_API_URL"] = api_url\n',
            'os.environ["PYTHONPATH"] = "/content/videoai/backend"\n',
            'os.environ["HOSTNAME"] = "0.0.0.0"\n',
            'HF_TOKEN = os.environ.get("HF_TOKEN") or getpass("Paste your Hugging Face token: ")\n',
            'os.environ["HF_TOKEN"] = HF_TOKEN\n',
            'os.environ["COLAB_T4_MODE"] = "true"\n',
            'os.environ["WAN_MODEL_ID"] = "Wan-AI/Wan2.1-T2V-1.3B-Diffusers"\n',
            'os.environ["WAN_DEFAULT_STEPS"] = "12"\n',
            'os.environ["ENABLE_COGVIDEO"] = "false"\n',
            'os.environ["ENABLE_LLM"] = "false"\n',
            'os.environ["JOB_TIMEOUT"] = "1800"\n',

            '\n',
            'print("Starting FastAPI Backend...")\n',
            'backend_process = subprocess.Popen(["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"], cwd="backend", stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n',
            'threading.Thread(target=stream_logs, args=(backend_process, "BACKEND"), daemon=True).start()\n',
            '\n',
            'print("Starting Celery Worker...")\n',
            'worker_process = subprocess.Popen(["celery", "-A", "workers.celery_app", "worker", "--loglevel=info"], cwd="backend", stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n',
            'threading.Thread(target=stream_logs, args=(worker_process, "WORKER"), daemon=True).start()\n',
            '\n',
            'print("Starting NextJS Frontend...")\n',
            'frontend_process = subprocess.Popen(["npm", "run", "dev"], cwd="frontend", stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)\n',
            'threading.Thread(target=stream_logs, args=(frontend_process, "FRONTEND"), daemon=True).start()\n',
            '\n',
            'time.sleep(10)\n',
            '\n',
            'frontend_proc, frontend_url = start_localtunnel(3000)\n',
            'print(f"==================================================")\n',
            'print(f"🚀 FRONTEND URL: {frontend_url}")\n',
            'print(f"==================================================")\n',
            '\n',
            'try:\n',
            '    while True:\n',
            '        time.sleep(1)\n',
            'except KeyboardInterrupt:\n',
            '    print("Shutting down...")\n',
            '    backend_process.terminate()\n',
            '    worker_process.terminate()\n',
            '    frontend_process.terminate()\n',
            '    api_proc.terminate()\n',
            '    frontend_proc.terminate()\n'
        ]

with open('Colab.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)
